// .kicad_pcb export — used only as an independent oracle (kicad-cli DRC) and for STEP/3D renders.
// The fabrication Gerbers come from gerber.ts, not from KiCad.
import { readFileSync, writeFileSync } from "node:fs";
import { Board, LAYERS, RULES } from "./board.ts";
import type { Part } from "./circuit.ts";
import { netClass } from "./router.ts";
import { rotate, pt } from "./geom.ts";

const STACKUP = readFileSync(new URL("./kicad_stackup.txt", import.meta.url), "utf8");
const PARTS = new URL("../parts/", import.meta.url).pathname;
const KICAD_3D = "/Applications/KiCad/KiCad.app/Contents/SharedSupport/3dmodels/";
/** EasyEDA STEP files KiCad can't render -> KiCad's own library model (origin = package centre). */
const MODEL_OVERRIDE: Record<string, { file: string; dx?: number }> = {
  C2678152: { file: KICAD_3D + "Package_DFN_QFN.3dshapes/QFN-48-1EP_7x7mm_P0.5mm_EP5.15x5.15mm.step" }, // iCE40UP5K-SG48
  // EasyEDA's model for this edge-launch SMA is a vertical body; KiCad's edge-mount SMA has its PCB edge at x = 2.1, ours at 2.6
  C496550: { file: KICAD_3D + "Connector_Coaxial.3dshapes/SMA_Samtec_SMA-J-P-H-ST-EM1_EdgeMount.step", dx: 0.5 },
};
const q = (s: string) => JSON.stringify(s);
const f = (v: number) => +v.toFixed(4);
let uid = 0;
const uuid = () => { const h = (++uid).toString(16).padStart(12, "0"); return `00000000-0000-4000-8000-${h}`; };

export function writeKicad(b: Board, path: string, title = "Muon3 station") {
  uid = 0;
  const nets = new Map<string, number>([["", 0]]);
  const nid = (n: string) => { if (!nets.has(n)) nets.set(n, nets.size); return nets.get(n)!; };
  for (const p of b.parts) for (const n of Object.values(p.pads)) nid(n);
  const o: string[] = [];
  o.push(`(kicad_pcb (version 20241229) (generator "muon3-hw") (generator_version "0.1")`,
    `(general (thickness 1.6) (legacy_teardrops no)) (paper "A4")`,
    `(title_block (title ${q(title)}) (rev "B") (company "Muon3 / GSU gLOWCOST") (comment 1 "Generated by hw/src/kicad.ts — oracle only; fab Gerbers come from gerber.ts"))`,
    STACKUP);
  for (const [n, i] of nets) o.push(`(net ${i} ${q(n)})`);
  for (const p of b.parts) o.push(footprint(b, p, nid));
  // edge
  o.push(`(gr_poly (pts ${b.outline.map(p => `(xy ${f(p.x)} ${f(p.y)})`).join(" ")}) (stroke (width 0.1) (type solid)) (fill no) (layer "Edge.Cuts") (uuid ${q(uuid())}))`);
  for (const h of b.holes) o.push(`(footprint "MountingHole" (layer "F.Cu") (uuid ${q(uuid())}) (at ${f(h.at.x)} ${f(h.at.y)}) (property "Reference" "H" (at 0 0 0) (layer "F.Fab") (hide yes) (uuid ${q(uuid())}) (effects (font (size 1 1)))) (attr exclude_from_pos_files exclude_from_bom) (pad "" np_thru_hole circle (at 0 0) (size ${h.d} ${h.d}) (drill ${h.d}) (layers "*.Cu" "*.Mask") (uuid ${q(uuid())})))`);
  for (const t of b.tracks) for (const s of t.path) {
    const L = q(LAYERS[t.layer]);
    if (s.kind === "seg") o.push(`(segment (start ${f(s.a.x)} ${f(s.a.y)}) (end ${f(s.b.x)} ${f(s.b.y)}) (width ${f(t.width)}) (layer ${L}) (net ${nid(t.net)}) (uuid ${q(uuid())}))`);
    else {
      const m = arcMid(s.a, s.b, s.c, s.ccw);
      o.push(`(arc (start ${f(s.a.x)} ${f(s.a.y)}) (mid ${f(m.x)} ${f(m.y)}) (end ${f(s.b.x)} ${f(s.b.y)}) (width ${f(t.width)}) (layer ${L}) (net ${nid(t.net)}) (uuid ${q(uuid())}))`);
    }
  }
  for (const v of b.vias) o.push(`(via (at ${f(v.at.x)} ${f(v.at.y)}) (size ${v.dia}) (drill ${v.drill}) (layers "F.Cu" "B.Cu") (net ${nid(v.net)}) (uuid ${q(uuid())}))`);
  for (const z of b.zones) o.push(`(zone (net ${nid(z.net)}) (net_name ${q(z.net)}) (layer ${q(LAYERS[z.layer])}) (uuid ${q(uuid())}) (hatch edge 0.5) (connect_pads yes (clearance ${RULES.clearance})) (min_thickness 0.15) (filled_areas_thickness no) (fill yes (thermal_gap 0.25) (thermal_bridge_width 0.3) (island_removal_mode 0)) (polygon (pts ${z.outline.map(p => `(xy ${f(p.x)} ${f(p.y)})`).join(" ")})))`);
  o.push(")");
  writeFileSync(path, o.join("\n") + "\n");
  writeFileSync(path.replace(/\.kicad_pcb$/, ".kicad_pro"), JSON.stringify(project(), null, 1));
  writeFileSync(path.replace(/\.kicad_pcb$/, ".kicad_dru"), dru());
}

function arcMid(a: { x: number; y: number }, b: { x: number; y: number }, c: { x: number; y: number }, ccw: boolean) {
  const r = Math.hypot(a.x - c.x, a.y - c.y);
  const a0 = Math.atan2(a.y - c.y, a.x - c.x);
  let sw = Math.atan2(b.y - c.y, b.x - c.x) - a0;
  if (ccw) { while (sw > 0) sw -= 2 * Math.PI; } else { while (sw < 0) sw += 2 * Math.PI; }
  return pt(c.x + r * Math.cos(a0 + sw / 2), c.y + r * Math.sin(a0 + sw / 2));
}

function footprint(b: Board, p: Part, nid: (n: string) => number): string {
  const pl = p.place!, fp = p.info.footprint;
  const out: string[] = [];
  out.push(`(footprint ${q("muon3:" + fp.name)} (layer "F.Cu") (uuid ${q(uuid())}) (at ${f(pl.x)} ${f(pl.y)} ${pl.rot})`);
  out.push(`(property "Reference" ${q(p.ref)} (at 0 0 ${pl.rot}) (layer "F.Fab") (uuid ${q(uuid())}) (effects (font (size 0.5 0.5) (thickness 0.08))))`);
  out.push(`(property "Value" ${q(p.value)} (at 0 0 ${pl.rot}) (layer "F.Fab") (hide yes) (uuid ${q(uuid())}) (effects (font (size 0.5 0.5))))`);
  out.push(`(property "LCSC" ${q(p.lcsc)} (at 0 0 0) (layer "F.Fab") (hide yes) (uuid ${q(uuid())}) (effects (font (size 0.5 0.5))))`);
  out.push(`(attr smd)`);
  for (const pd of fp.pads) {
    const net = p.pads[pd.num];
    const netS = net ? ` (net ${nid(net)} ${q(net)})` : "";
    const ang = (pd.rot + pl.rot) % 360;
    const layers = pd.layer === "multi" ? `"*.Cu" "*.Mask"` : pd.layer === "bottom" ? `"B.Cu" "B.Paste" "B.Mask"` : `"F.Cu" "F.Paste" "F.Mask"`;
    const kind = pd.layer === "multi" ? "thru_hole" : "smd";
    const drill = !pd.drill ? "" : pd.drillLen && pd.drillLen > pd.drill + 1e-3
      ? (pd.h >= pd.w ? ` (drill oval ${f(pd.drill)} ${f(pd.drillLen)})` : ` (drill oval ${f(pd.drillLen)} ${f(pd.drill)})`)
      : ` (drill ${f(pd.drill)})`;
    if (pd.shape === "poly" && pd.poly?.length) {
      const pts = pd.poly.map(v => { const r = rotate(pt(v.x - pd.x, v.y - pd.y), -pd.rot * 0); return `(xy ${f(r.x)} ${f(r.y)})`; }).join(" ");
      out.push(`(pad ${q(pd.num)} ${kind} custom (at ${f(pd.x)} ${f(pd.y)} ${pl.rot}) (size 0.1 0.1)${drill} (layers ${layers}) (options (clearance outline) (anchor circle)) (primitives (gr_poly (pts ${pts}) (width 0) (fill yes)))${netS} (uuid ${q(uuid())}))`);
    } else {
      const shape = pd.shape === "rect" ? "rect" : pd.shape === "oval" ? "oval" : "circle";
      out.push(`(pad ${q(pd.num)} ${kind} ${shape} (at ${f(pd.x)} ${f(pd.y)} ${ang}) (size ${f(pd.w)} ${f(pd.h)})${drill} (layers ${layers})${netS} (uuid ${q(uuid())}))`);
    }
  }
  for (const h of fp.holes) out.push(`(pad "" np_thru_hole circle (at ${f(h.x)} ${f(h.y)}) (size ${f(h.d)} ${f(h.d)}) (drill ${f(h.d)}) (layers "*.Cu" "*.Mask") (uuid ${q(uuid())}))`);
  const bb = fp.bbox;
  out.push(`(fp_rect (start ${f(bb.x0)} ${f(bb.y0)}) (end ${f(bb.x1)} ${f(bb.y1)}) (stroke (width 0.05) (type solid)) (fill no) (layer "F.CrtYd") (uuid ${q(uuid())}))`);
  const m = fp.model, step = PARTS + (p.info.lcsc) + "/model.step";
  const ov = MODEL_OVERRIDE[p.info.lcsc];
  if (ov) out.push(`(model ${q(ov.file)} (offset (xyz ${ov.dx ?? 0} 0 0)) (scale (xyz 1 1 1)) (rotate (xyz 0 0 0)))`);
  else if (m) out.push(`(model ${q(step)} (offset (xyz ${f(m.ox)} ${f(-m.oy)} ${f(m.z)})) (scale (xyz 1 1 1)) (rotate (xyz ${m.rot.map(v => -v).join(" ")})))`);
  out.push(")");
  return out.join(" ");
}

function project() {
  const hvNets = ["HV", "HV_FB_MID", "HVJ0", "HVJ1", "HVJ2", "HVJ3", "HV_MON_MID"];
  return {
    board: { design_settings: { rules: {
      min_clearance: RULES.clearance, min_track_width: 0.12, min_via_diameter: 0.45, min_through_hole_diameter: 0.3,
      min_via_annular_width: 0.1, min_copper_edge_clearance: RULES.edge, min_hole_clearance: 0.2, min_hole_to_hole: 0.25,
      min_connection: 0.12, max_error: 0.005, solder_mask_to_copper_clearance: 0, min_silk_clearance: 0,
    } } },
    net_settings: {
      classes: [
        { name: "Default", clearance: RULES.clearance, track_width: RULES.track, via_diameter: RULES.viaDia, via_drill: RULES.viaDrill, priority: 2147483647 },
        { name: "HV", clearance: 0.26, track_width: netClass("HV").width, via_diameter: RULES.viaDia, via_drill: RULES.viaDrill, priority: 0 },
      ],
      netclass_patterns: hvNets.map(n => ({ netclass: "HV", pattern: n })),
      meta: { version: 4 },
    },
    meta: { filename: "muon3.kicad_pro", version: 3 },
  };
}

function dru() {
  return `(version 1)
# Manufacturer land patterns (EasyEDA/LCSC) are accepted as-is between pads of the same part.
(rule "intra-footprint pads" (constraint clearance (min 0.08mm)) (condition "A.Type == 'Pad' && B.Type == 'Pad' && A.Parent == B.Parent"))
(rule "intra-footprint holes" (constraint hole_clearance (min 0.1mm)) (condition "A.Type == 'Pad' && B.Type == 'Pad' && A.Parent == B.Parent"))
# Edge-launch SMA: its land pattern runs to the board edge by design.
(rule "edge SMA" (constraint edge_clearance (min 0.15mm)) (condition "A.Type == 'Pad' && A.Library_Link == 'muon3:SMA-SMD_BWSMA-KE-P001'"))
`;
}
