"""Exports the simulation results used by the music video: src/data.rs (consts).
Needs the repo's sim outputs plus numpy, scipy, matplotlib, Pillow. Usage: python tools/export_data.py [scope/muon.txt]"""
import json, os, sys, importlib.util, math
import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
out = []
def arr(name, rows, ty="f32"):
    out.append(f"pub const {name}: [[{ty}; 2]; {len(rows)}] = [" + ", ".join(f"[{a:.3f}, {b:.3f}]" for a, b in rows) + "];")

# ---- tile outlines and the fiber loop of tile 01 (mm, centred on the bounding box) ----
def P(n): return json.load(open(f"{ROOT}/sim/geant4/gdml/mesh/InnerHCalTile{n:02d}_EJ200_mesh.json"))["params"]
p1 = P(1); hull = np.array(p1["hull_xy"], float); c = 0.5 * (hull.min(0) + hull.max(0))
fib = np.array(p1["fiber_path_xy"], float) - c
keep = [0] + [i for i in range(1, len(fib)) if np.hypot(*(fib[i] - fib[i - 1])) > 0.0] ; fib = fib[::3]
arr("TILE01_HULL", hull - c); arr("TILE01_FIBER", fib)
hulls = {}
for n in range(1, 13):
    h = np.array(P(n)["hull_xy"], float); h -= 0.5 * (h.min(0) + h.max(0)); hulls[n] = h
    arr(f"HULL_{n:02d}", h)

# ---- stack rate at 100 mm aligned, all 12 shapes (same model as sim/python/stack_permutations.py) ----
rng = np.random.default_rng(1); N = 200_000
def inside(poly, x, y):
    ok = np.ones(x.shape, bool)
    for i in range(len(poly)):
        (ax, ay), (bx, by) = poly[i], poly[(i + 1) % len(poly)]; ok &= (bx - ax) * (y - ay) - (by - ay) * (x - ax) >= 0
    return ok
rates = []
for n in range(1, 13):
    b = hulls[n]; A = 0.5 * abs(np.dot(b[:, 0], np.roll(b[:, 1], -1)) - np.dot(b[:, 1], np.roll(b[:, 0], -1))) / 100
    x0, y0 = b.min(0); x1, y1 = b.max(0); x = rng.uniform(x0, x1, 3 * N); y = rng.uniform(y0, y1, 3 * N); m = inside(b, x, y)
    x, y = x[m][:N], y[m][:N]; ct = np.maximum((1 - rng.uniform(size=N)) ** 0.25, 0.26); st = np.sqrt(1 - ct ** 2); ph = rng.uniform(0, 2 * np.pi, N)
    dx, dy = st / ct * np.cos(ph), st / ct * np.sin(ph)
    ok = inside(b, x + 100 * dx, y + 100 * dy) & inside(b, x + 200 * dx, y + 200 * dy)
    rates.append(0.0070 * A * math.pi / 2 * ok.mean() * 3600)
out.append("pub const STACK_RATE_PER_H: [f32; 12] = [" + ", ".join(f"{r:.0f}.0" for r in rates) + "];")

# ---- ngspice pulse: one muon (36.6 p.e.) through the TIA and the comparator ----
scope = sys.argv[1] if len(sys.argv) > 1 else None
if scope and os.path.exists(scope):
    d = np.loadtxt(scope, skiprows=1); t, tia, hit = d[:, 0] * 1e9, d[:, 1], d[:, 2]
    sel = (t >= 200) & (t <= 760); idx = np.linspace(np.flatnonzero(sel)[0], np.flatnonzero(sel)[-1], 140).astype(int)
    out.append("/// (ns since 200 ns, TIA mV below its 2.5 V rest level, comparator output 0..1)")
    out.append(f"pub const PULSE: [[f32; 3]; {len(idx)}] = [" + ", ".join(f"[{t[i]-200:.1f}, {(2.5-tia[i])*1000:.1f}, {min(1,hit[i]/3.3):.2f}]" for i in idx) + "];")

# ---- thermal field of the board (Wi-Fi on): 2 mm cells, 0..250 = 0..max K, 255 = no board (slots) ----
spec = importlib.util.spec_from_file_location("thermal", f"{ROOT}/hw/sim/thermal.py"); th = importlib.util.module_from_spec(spec); spec.loader.exec_module(th)
th.SRC.update(th.PROFILES["wifi-on"]); g, air, bme = th.solve("A")
ny, nx = g.shape; k = 4; cells = np.full((ny // k, nx // k), 255, int)
for i in range(ny // k):
    for j in range(nx // k):
        blk = g[i * k:(i + 1) * k, j * k:(j + 1) * k]
        if np.isfinite(blk).mean() > 0.5: cells[i, j] = int(round(250 * np.nanmean(blk) / np.nanmax(g)))
out.append(f"pub const THERMAL: [[u8; {cells.shape[1]}]; {cells.shape[0]}] = [" + ", ".join("[" + ",".join(map(str, r)) + "]" for r in cells) + "];")
out.append(f"pub const THERMAL_MAX_K: f32 = {np.nanmax(g):.1f};  pub const THERMAL_BME_K: f32 = {bme:.1f};")
open(f"{HERE}/../src/data.rs", "w").write("// generated by tools/export_data.py, do not edit\n#![allow(dead_code)]\n" + "\n".join(out) + "\n")
print("rates/h @100 mm:", [round(r) for r in rates], "thermal max", round(float(np.nanmax(g)), 1), "bme", round(bme, 1))
