// parts/INDEX.md: every part on the board, with its local datasheet, 3D model and source links.
import { existsSync, writeFileSync, statSync } from "node:fs";
import { build } from "../src/design.ts";

const ROOT = new URL("../parts/", import.meta.url).pathname;
const c = await build();
const rows = new Map<string, { refs: string[]; value: string; mpn: string; mfr: string; pkg: string; ds: string; cls: string; fp: string }>();
for (const p of c.parts) {
  const r = rows.get(p.lcsc) ?? { refs: [], value: p.value, mpn: p.info.mpn, mfr: p.info.manufacturer, pkg: p.info.footprint.name, ds: p.info.datasheet, cls: p.info.jlcClass, fp: p.info.lcsc };
  r.refs.push(p.ref); rows.set(p.lcsc, r);
}
const nat = (a: string, b: string) => a.localeCompare(b, undefined, { numeric: true });
const kb = (f: string) => (existsSync(f) ? `${Math.round(statSync(f).size / 1024)} kB` : "—");
const lines = [
  "# Muon3 station — parts library",
  "",
  "Generated by `bun tools/parts_index.ts`. Each `parts/<LCSC>/` folder holds `part.json` (footprint in mm + pin names, from LCSC/EasyEDA),",
  "`datasheet.pdf`, `model.step` and `model.obj`. Passives share one footprint/3D model per package (the folder named in *Footprint from*).",
  "TI parts also have `datasheet_full.pdf` where LCSC's copy is abridged.",
  "",
  "| Refs | Value | MPN | Manufacturer | Package | LCSC | Footprint from | Datasheet | STEP |",
  "|---|---|---|---|---|---|---|---|---|",
];
for (const [lcsc, r] of [...rows].sort((a, b) => nat(a[1].refs[0], b[1].refs[0]))) {
  const dir = ROOT + r.fp + "/";
  const ds = existsSync(ROOT + lcsc + "/datasheet_full.pdf") ? `[full](${lcsc}/datasheet_full.pdf)` : existsSync(dir + "datasheet.pdf") ? `[pdf](${r.fp}/datasheet.pdf) (${kb(dir + "datasheet.pdf")})` : r.ds ? `[link](${r.ds})` : "—";
  lines.push(`| ${r.refs.sort(nat).join(", ")} | ${r.value} | ${r.fp === lcsc ? r.mpn : "(generic)"} | ${r.fp === lcsc ? r.mfr : ""} | ${r.pkg} | [${lcsc}](https://jlcpcb.com/partdetail/${lcsc}) | ${r.fp === lcsc ? "" : r.fp} | ${ds} | ${existsSync(dir + "model.step") ? `[step](${r.fp}/model.step)` : "—"} |`);
}
writeFileSync(ROOT + "INDEX.md", lines.join("\n") + "\n");
console.log(`${rows.size} line items -> parts/INDEX.md`);
